baseURL = "https://blog.knychalski.me"  
title = "xkjh Blog"  
theme = "LoveIt"
languageCode = "en"                 

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

[params]
  version = "0.2.X"
  defaultTheme = "auto"
  
  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      name = "xkjh blog"     
      pre = "<i class='fas fa-shield-alt fa-fw'></i>" 
  [params.footer]
    enable = true
    copyright = true
    author = true