baseURL = "https://knychalski.me"  # Tu wpiszesz swoją domenę z Cloudflare
title = "xkjh Blog"  # Tytuł Twojej strony
theme = "LoveIt"
languageCode = "en"                 # Język strony

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

[params]
  version = "0.2.X"
  # Tutaj motyw automatycznie dopasuje tryb ciemny/jasny do preferencji systemowych czytelnika
  defaultTheme = "auto"
  
  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      name = "Security Journey"     # Nazwa widoczna w lewym górnym rogu
      pre = "<i class='fas fa-shield-alt fa-fw'></i>" # Ikona tarczy obok nazwy

  [params.footer]
    enable = true
    copyright = true
    author = true